name: Hourly Poster image

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4 playwright Pillow
          playwright install chromium --with-deps

      - name: Run Bot
        env:
          EX_COOKIES: ${{ secrets.EX_COOKIES }}
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
        run: python bot.py

      - name: Commit and Push History
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Git pull error fix
          git stash || echo "No changes to stash"
          git pull origin main --rebase || echo "No rebase needed"
          git stash pop || echo "Nothing to pop"
          
          touch posted_urls.txt
          git add posted_urls.txt
          git commit -m "Update history ***skip ci***" || echo "No changes"
          git push origin main
